Repository clouway/kcqrs, pull requests merged in 2018-05, with the labels that each got.

#24 kcqrs: bulk loading of aggregates
  gradle.properties
  kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt
  kcqrs-appengine/src/test/java/com/clouway/kcqrs/adapter/appengine/AppEngineEventStoreTest.kt
  kcqrs-client/src/main/kotlin/com/clouway/kcqrs/client/HttpEventStore.kt
  kcqrs-client/src/test/kotlin/HttpEventStoreTest.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/EventStore.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/SimpleAggregateRepository.kt
  kcqrs-core/src/test/kotlin/com/clouway/kcqrs/core/SimpleAggregateRepositoryTest.kt
  kcqrs-testing/src/main/kotlin/com/clouway/kcqrs/testing/InMemoryEventStore.kt
Labels: needs-review

#25 kcqrs: bulk loading in AggregateRepository
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/AuditAwareAggregateRepository.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/SimpleAggregateRepository.kt
  kcqrs-core/src/test/kotlin/com/clouway/kcqrs/core/SimpleAggregateRepositoryTest.kt
  kcqrs-testing/src/main/kotlin/com/clouway/kcqrs/testing/InMemoryEventStore.kt
Labels: needs-review

#26 kcqrs: bulk loading of aggregates
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/AggregateRepository.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/AuthoredAggregateRepository.kt
  kcqrs-testing/src/main/kotlin/com/clouway/kcqrs/testing/InMemoryAggregateRepository.kt
  kcqrs-testing/src/test/kotlin/com/clouway/kcqrs/testing/InMemoryAggregateRepositoryTest.kt
Labels: needs-review

#27 kcqrs: bulk loading of aggregates which not exist
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/AggregateNotFoundException.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/AggregateRepository.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/AuditAwareAggregateRepository.kt
  kcqrs-testing/src/main/kotlin/com/clouway/kcqrs/testing/InMemoryAggregateRepository.kt
  kcqrs-testing/src/test/kotlin/com/clouway/kcqrs/testing/InMemoryAggregateRepositoryTest.kt
Labels: needs-review

#28 kcqrs-core: command validation during sending
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/CommonValidators.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/MessageBus.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/SimpleMessageBus.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/Validation.kt
  kcqrs-core/src/main/kotlin/com/clouway/kcqrs/core/ViolationErrorException.kt
  kcqrs-core/src/test/kotlin/com/clouway/kcqrs/core/CommonValidatorsTest.kt
  kcqrs-core/src/test/kotlin/com/clouway/kcqrs/core/SimpleMessageBusTest.kt
  kcqrs-core/src/test/kotlin/com/clouway/kcqrs/core/ValidationTest.kt
  kcqrs-testing/src/main/kotlin/com/clouway/kcqrs/testing/InMemoryMessageBus.kt
Labels: needs review

#30 kcqrs: allow saving of strings with any length
  kcqrs-appengine/src/main/kotlin/com/clouway/kcqrs/adapter/appengine/AppEngineEventStore.kt
  kcqrs-appengine/src/test/java/com/clouway/kcqrs/adapter/appengine/AppEngineEventStoreTest.kt
Labels: reviewed
